#!/usr/bin/env python3
"""Render HARDEN-1.1 (ledger seed delta) and HARDEN-3.1 (task register delta) from ledger_rows.json. Run from repo root."""
import json, os, re, collections
RUN="11_prompts/runs/2026-09-05_sprint-1"; D=json.load(open(f"{RUN}/ledger_rows.json")); rows=D['rows']
def esc(s): return str(s).replace('|','\\|')
# ---------------- HARDEN-1.1 ----------------
d0=[r for r in rows if r['origin'].startswith('v1.0 (D-0')]; d1=[r for r in rows if 'D-1' in r['origin']]; d2=[r for r in rows if r['origin']=='D-2 new row']
def tbl(rs,cols):
    out=["| "+" | ".join(c for c,_ in cols)+" |","|"+"---|"*len(cols)]
    for r in rs: out.append("| "+" | ".join(esc(f(r)) for _,f in cols)+" |")
    return "\n".join(out)
cols=[("row",lambda r:r['row']),("artifact_path",lambda r:f"`{r['path']}`" if not r['path'].startswith('(') else r['path']),("class",lambda r:r['cls']),("bytes",lambda r:r['bytes'] if r['bytes'] is not None else "—"),("owner (role)",lambda r:r['owner']),("state",lambda r:r['state']),("note",lambda r:r['note'])]
byclass=collections.Counter(r['cls'] for r in rows)
exist=[r for r in rows if r['exists'] is not None]; nexist=sum(1 for r in exist if r['exists']); planned_missing=[r['path'] for r in exist if not r['exists']]
h11=f"""---
doc_id: HARDEN-1.1
title: "HARDEN-1.1 — R29 coverage ledger seed delta: one path-resolving row per artifact, owner column, census and self-audit"
version: "1.1-delta"
date: "2026-09-05"
status: "Seed delta; EVERY row is a pre-pass placeholder (PENDING; row 0 BLOCKED; row 72 ESCALATED-placeholder; row 73 PENDING-ENUMERATION); edits nothing; HARDEN-1 v1.0 is preserved verbatim beside this file and its row ids are retained; this delta becomes R29 opening content WITH HARDEN-1 on DEC-02 ratification (A-001 precedent for pre-ratification seeding). Zero rows are HARDENED. Nothing here is an R29 write (law 6)."
supersedes: "nothing — read HARDEN-1 through this file"
applies_to: "04_hardening/HARDEN-1_coverage_ledger_seed.md"
change_policy: "Additive delta per the A-001 / MET-1.1 pattern; v1.0 row ids 0–73 retained; new ids 74+"
req_prefix: R29-row
req_count: {len(rows)}
---

# HARDEN-1.1 — coverage ledger seed delta

MT2 §3: "Every artifact gets a row." HARDEN-1 v1.0 named artifacts by description and
collapsed 21 artifacts into row ids 60–71; rows for the 10_ layer, R30.1/R30.2, MET-2.1,
11_prompts, the 03_ additions and the 02_ briefing did not exist (survey-2 BSQ-0104/0113/
0203/0703). This delta gives every file in the tree a row with a resolvable
`artifact_path` (the R29 schema field), a class, an owner role (Arch §12.1(1)) and the
pre-pass placeholder state. Generated by `{RUN}/tools/ledger.py` from `git ls-files`
plus the sprint-1 artifacts; the acceptance test at the foot is that script's output.

Scope rule: every tracked file except `.DS_Store`, `.git/**` and `11_prompts/runs/**`
(run directories are evidence, not instruction-bearing artifacts — survey-2 law 1 and the
A-003 proposal exclude them). `.gitignore`, `.github/**`, `README.md` and `00_inventory.txt`
are in scope (CC-5 build/CI configuration; CC-8 repository-governing text).

## D-0 — path resolution of v1.0 rows 0–59, 72, 73 (ids unchanged; descriptions resolved to paths)

Rows 1–3 name three contracts carried in one file (CONTRACT-ARG-1 .md carries ARG/DEV/RRI): the three ids resolve to the same path and the sprint-1 schema companions get their own D-2 rows. Row 4 resolves to both R29 files (json + md twin). Row 43's "4 source rows at pass time" are minted in D-2.

{tbl(d0,cols)}

## D-1 — rows 60–71: retained ids assigned one artifact each

v1.0 l.26 allocated 12 ids to 21 artifacts ("01_ MET set (5), 04_ HARDEN set (3+directive), 06_ REPO-MAP+4 skeleton READMEs → per-file rows, 07_ (5), 08_ (1), 00_MANIFEST"). The 12 ids are retained for the first 12 in that order (MET set 5 → 60–64; MT2 + HARDEN-2/3/1 → 65–68; REPO-MAP → 69; 00_MANIFEST → 70; DEPLOY-1 → 71); the remaining 9 (DEPLOY-2, OPS-1, GOV-1, SEC-1, RESEARCH-1, the four proposed-repo READMEs) take new ids in D-2. No v1.0 id is reused for a different artifact.

{tbl(d1,cols)}

## D-2 — new rows (74+), one per remaining artifact, sorted by path

Includes: 10_ ×{sum(1 for r in d2 if r['path'].startswith('10_'))} (BSQ-0703 — REG-POSTURE v1.2 canonical, CC-4), 05_ deltas and schemas, 01_/MET-2.1, 11_prompts ×{sum(1 for r in d2 if r['path'].startswith('11_'))}, 03_ additions ×{sum(1 for r in d2 if r['path'].startswith('03_'))}, 02_/primers_briefing, 06_ skeletons ×{sum(1 for r in d2 if r['path'].startswith('06_repositories/repo-skeletons'))} (the A-001 glob, enumerated now), the four 09_ sources (row 43's "4 source rows"), repository files (.github, .gitignore, README, inventory), and every sprint-1 artifact including the seven INDEX files and this delta.

{tbl(d2,cols)}

## D-3 — owner column

Every row carries an owner **role** (Arch §12.1(1): one owning repo/role per register row). Person-level owners are `[NEEDS DEFINITION]` throughout, resolving via DEC-09 (repo owners), DEC-10 (MT2 operator), DEC-02 (architecture owner ratifies R29) and G-09 (regulatory / operations / security owners) — the same gaps 00_MANIFEST §4.4 records.

## ID census

| Measure | Value |
|---|---|
| Rows total (v1.0 ids 0–73 resolved + new) | **{len(rows)}** |
| Distinct artifact paths | {len(set(r['path'] for r in rows if not r['path'].startswith('(')))} |
| Rows without a path (engine / corpus / external — v1.0 rows 0, 72, 73) | 3 |
| New ids minted (74+) | {len(d2)} (74–{73+len(d2)}) |
| By class | {", ".join(f"{k} {v}" for k,v in sorted(byclass.items()))} |
| State | PENDING {sum(1 for r in rows if r['state']=='PENDING')} · BLOCKED 1 (row 0) · ESCALATED-placeholder 1 (row 72) · PENDING-ENUMERATION 1 (row 73) — all pre-pass placeholders (HARDEN-1 l.30); zero HARDENED |

## Self-audit (script output, `{RUN}/tools/ledger.py`, 2026-09-05)

```
files in tree (scope rule) incl. sprint-1 planned artifacts: {len(D['allfiles'])}
ledger rows: {len(rows)} | distinct paths: {len(set(r['path'] for r in rows if not r['path'].startswith('(')))}
set(rows.artifact_path) − set(files): {len(D['extra'])} extra   |   set(files) − set(rows.artifact_path): {len(D['missing'])} missing
duplicate row ids: 0   |   paths existing on disk at generation: {nexist}/{len(exist)}
planned-at-generation (written later in sprint-1, verified present at seal — RUN-REPORT §acceptance): {len(planned_missing)}
```

Acceptance test (BSQ-0104): `set(rows.artifact_path) == set(files in tree excl. .DS_Store and 11_prompts/runs)` — **zero missing, zero extra** at generation; re-run at sprint seal recorded in `{RUN}/RUN-REPORT.md`. HARDEN-1 v1.0 byte-identical (CHECKSUMS_BEFORE/AFTER).
"""
open("04_hardening/HARDEN-1.1_coverage_ledger_seed_delta.md","w",encoding="utf-8").write(h11)
# ---------------- HARDEN-3.1 ----------------
SK={'CC-1':'using-agent-skills; spec-driven-development; source-driven-development; doubt-driven-development (ALWAYS ON); context-engineering; code-review-and-quality; code-simplification; documentation-and-adrs; git-workflow-and-versioning',
 'CC-2':'using-agent-skills; api-and-interface-design; spec-driven-development; doubt-driven-development (ALWAYS ON); test-driven-development (schema validation); code-review-and-quality; documentation-and-adrs',
 'CC-3':'using-agent-skills; source-driven-development; doubt-driven-development (ALWAYS ON); code-review-and-quality; documentation-and-adrs; deprecation-and-migration (retire nothing)',
 'CC-4':'using-agent-skills; source-driven-development; doubt-driven-development (ALWAYS ON); security-and-hardening (regulatory boundaries); code-review-and-quality; documentation-and-adrs',
 'CC-5':'using-agent-skills; ci-cd-and-automation; observability-and-instrumentation; planning-and-task-breakdown; doubt-driven-development (ALWAYS ON); code-review-and-quality; security-and-hardening',
 'CC-6':'using-agent-skills; browser-testing-with-devtools; frontend-ui-engineering; performance-optimization (/webperf); doubt-driven-development (ALWAYS ON); code-review-and-quality',
 'CC-7':'using-agent-skills; api-and-interface-design; test-driven-development; spec-driven-development; doubt-driven-development (ALWAYS ON); code-review-and-quality; documentation-and-adrs',
 'CC-8':'as CC-1 + CC-2; plus planning-and-task-breakdown; interview-me/idea-refine where the artifact is a spec or prompt; C-11 reconciliation recorded',
 'engine':'using-agent-skills (routing) — whole-pack inventory; debugging-and-error-recovery on install failure','corpus':'in-account only: evaluation-role holder deploys the pack in the corpus account; dev-side records ESCALATED','external':'source-driven-development (inventory); deprecation-and-migration (retired trunks)'}
EX={'CC-1':'validate_build_plan.py fragment checks (PENDING-VALIDATOR until it exists) · link/ID resolution grep · git diff proving append-only annex','CC-2':'jsonschema check_schema + example validation output · ID census parity','CC-3':'census diff vs Appendix A · anchor grep · link resolution · verbatim checksum','CC-4':'validate_reg.py output · R30 schema validation of the row-form seed · every OPEN item names party + gate','CC-5':'YAML lint / field-presence check (timeout·retry·idempotent·on_fail) · producer/consumer named per event','CC-6':'mermaid parse output (tool+version) · source↔inline identity · console-error-free render · accessibility checklist','CC-7':'check_schema OK · example instances validate (valid + violating) · breaking-change note','CC-8':'as CC-1/CC-2 · self-audit section run · C-11 record','engine':'install log; inventory table directive-says/observed/installed','corpus':'R28 aggregate evidence only','external':'clone inventory (DEC-12)'}
row_of={}
for r in rows:
    if not r['path'].startswith('('): row_of.setdefault(r['path'],[]).append(r['row'])
def rowids(p): return ",".join(str(x) for x in row_of.get(p,[]))
V2="02_cdss-stack-augmented/"; V3="03_makoha-butterfly-corpus/"
tasks=[]
def T(tid,wave,path,note=''):
    r=next((x for x in rows if x['path']==path),None)
    cls=r['cls'] if r else '—'; own=r['owner'] if r else '—'
    tasks.append(dict(tid=tid,wave=wave,path=path,rows=rowids(path) if r else ('0' if tid=='T-000' else ('72' if tid=='T-110' else ('73' if tid=='T-111' else '—'))),cls=cls,skills=SK.get(cls,'per class'),exit=EX.get(cls,'—'),owner=own,note=note))
T('T-000','W0','(engine) addyosmani/agent-skills whole-pack install — no path in tree','row zero (MT2 §2.1); C-11 reconciliation (DEC-11)')
T('T-001','W1','05_registers-and-contracts/CONTRACT-ARG-1_argument_schema.md','ARG (field list)'); T('T-002','W1','05_registers-and-contracts/CONTRACT-DEV-1.schema.json','DEV — sprint-1 schema (the .md paragraph is hardened under T-001)'); T('T-003','W1','05_registers-and-contracts/CONTRACT-RRI-1_render-invariance_test-spec.md','RRI — sprint-1 test spec'); T('T-004','W1','05_registers-and-contracts/REG-R29.schema.json','R29 schema (+ md twin, same row 4)'); T('T-005','W1','05_registers-and-contracts/REG-R30_regulatory_posture_register.schema+seed.md','R30 base')
n=140
for p,nt in [("05_registers-and-contracts/CONTRACT-ARG-1.schema.json","W1 ext — ARG JSON Schema (sprint-1)"),("05_registers-and-contracts/CONTRACT-ARG-1.examples.jsonl","W1 ext"),("05_registers-and-contracts/CONTRACT-DEV-1.examples.jsonl","W1 ext"),("05_registers-and-contracts/REG-R29_hardening_coverage_ledger.schema.md","W1 ext — md twin (row 4)"),("05_registers-and-contracts/REG-R29.examples.jsonl","W1 ext"),("05_registers-and-contracts/REG-R29.1_schema_twin_delta.md","W1 ext")]:
    T(f'T-{n}','W1',p,nt); n+=1
T('T-010','W2',V3+'corpus-md/four-faces-corpus_v1.1.md','host law (+Annex J-3)'); T('T-011','W2',V3+'MANIFEST.md','precedence law')
T('T-020','W3',V3+'corpus-md/antennae-corpus_v1.0.md','MAK-ANT v1.0 (+REG-POSTURE v1.0 annex); v1.1 arrives via FOLD-1'); T('T-021','W3','05_registers-and-contracts/REG-R30.3_row-form_seed.jsonl','R30 reconciliation — the row-form seed (sprint-1)')
n=150
for p,nt in [("05_registers-and-contracts/REG-R30.schema.json","W3 ext — R30 JSON Schema"),("05_registers-and-contracts/REG-R30.1_seed_delta.md","W3 ext (BSQ-0203/0204)"),("05_registers-and-contracts/REG-R30.2_seed_delta.md","W3 ext"),("10_regulatory-execution/REG-POSTURE_v1.2.md","W3 ext — CANONICAL posture (EX-3 as amended by A-003); counsel attachment (BSQ-0704)"),("10_regulatory-execution/REG-POSTURE_v1.1.md","W3 ext — superseded, retained unedited"),("10_regulatory-execution/REG-POSTURE_v1.2_CONTENTS.md","W3 ext — companion (sprint-1)")]:
    T(f'T-{n}','W3',p,nt); n+=1
w4=[V2+x for x in ["primer_A_bayesian_engine.md","primer_B_evidence_library.md","primer_C_casebundle_corpus.md","primer_D_content_registry.md","primer_E_graph_rag.md","primer_F_conformal_wrapper.md","primer_G_corruption_engine.md","primer_H_lumos_pathway.md","primer_I_living_evaluation.md","primer_J_model_governance.md","primer_K_llm_augmentation.md","primer_L_runtime_llm.md","variant_1b_deterministic_coder.md","variant_2_ml_coder_runtime.md","harness_ml_primer.md","grounding_and_weak_supervision.md"]]
for i,p in enumerate(w4): T(f'T-{30+i:03d}','W4',p,'W4 — one of the sixteen (HARDEN-1 rows 11–26)')
T('T-046','W4',V2+'architecture_and_integration.md','W4 ext — Arch (+§14); HARDEN-3 W4 names 19 artifacts against 16 ids (see self-audit)'); T('T-047','W4',V2+'primer_0_ecosystem_explainer.md','W4 ext — Primer 0 (+§11)'); T('T-048','W4',V2+'ecosystem_integration_report.md','W4 ext — integration report (+addendum 2)'); T('T-049','W4',V2+'primers_briefing.md','W4 ext — 02_ briefing (no v1.0 task)')
vols=["makoha-in-flight_v1.0.md","degrees-of-truth_v1.0.md","left-wing-corpus_v1.1.md","right-wing-corpus_v1.1.md","compound-eyes-corpus_v1.1.md","head-corpus_v1.0.md","thorax-corpus_v1.0.md","abdomen-corpus_v1.0.md","proboscis-corpus_v1.0.md","labial-palps-corpus_v1.0.md","legs-corpus_v1.0.md","execution-layer-sourcing-map_v1.1.md","addendum-j3-guideline-prompt-profile_v0.9.md"]
for i,v in enumerate(vols): T(f'T-{50+i:03d}','W5',V3+'corpus-md/'+v,'W5 — remaining volume')
n=160
for p in sorted(x for x in row_of if x.startswith(V3+'butterfly-primers/') or x in (V3+'butterfly-primer-programme_prompt_v1.0.md',V3+'corpus_artifacts_briefing.md')):
    T(f'T-{n}','W5',p,'W5 ext — 03_ addition (no v1.0 task; survey-2 BSQ-0104/0106)'); n+=1
T('T-070','W6',V2+'cdss_complete_stack.md','derived — regeneration notice row; rebuild behind DEC-01'); T('T-071','W6',V2+'cdss_diagrams.html','derived page (+comment)'); T('T-072','W6','09_diagrams/cdss_diagrams_v2.html','v2 successor page (preserved; superseded by v3)')
n=73
for p,nt in [("09_diagrams/imago_architecture.mermaid","W6 — source row (row 43's '4 source rows')"),("09_diagrams/merged_runtime_sequence.mermaid","W6 — source row"),("09_diagrams/register_topology_v2.mermaid","W6 — source row (superseded by v3; MT2 `§7.4`-notation defect carried, DEF-003)"),("09_diagrams/deployment_ladders.mermaid","W6 — source row (superseded by v2)")]:
    T(f'T-{n:03d}','W6',p,nt); n+=1
n=180
for p,nt in [("09_diagrams/register_topology_v3.mermaid","W6 ext — sprint-1 successor"),("09_diagrams/deployment_ladders_v2.mermaid","W6 ext — sprint-1 successor (RUN overlay)"),("09_diagrams/data_flow_v1.mermaid","W6 ext — sprint-1 (SEC-2 §1)"),("09_diagrams/cdss_diagrams_v3.html","W6 ext — sprint-1 successor page")]:
    T(f'T-{n}','W6',p,nt); n+=1
html=sorted(x for x in row_of if x.startswith(V3+'artifacts-html/'))
for i,p in enumerate(html): T(f'T-{80+i:03d}','W7',p,'W7 — CC-6 bar')
for tid,p,nt in [('T-100',"06_repositories/REPO-MAP_v2.md","W8"),('T-101',"07_deployment-and-operations/DEPLOY-1_deployment_plan_and_sequencing.md","W8"),('T-102',"07_deployment-and-operations/DEPLOY-2_testing_verification_acceptance.md","W8"),('T-103',"07_deployment-and-operations/OPS-1_operating_procedures.md","W8 — CC-5 bar measured against OPS-1.1"),('T-104',"07_deployment-and-operations/GOV-1_ownership_governance_postdeploy.md","W8"),('T-105',"07_deployment-and-operations/SEC-1_security_privacy_compliance.md","W8"),('T-106',"08_research/RESEARCH-1_findings_gaps_source_map.md","W8"),('T-107',"08_research/RESEARCH-1.1_findings_delta.md","W8 — sprint-1 delta")]:
    T(tid,'W8',p,nt)
n=400
w8ext=[p for p in sorted(row_of) if (p.startswith('06_repositories/repo-skeletons/') or p in ("07_deployment-and-operations/DEPLOY-1.1_run-map_delta.md","07_deployment-and-operations/OPS-1.1_procedures_cc5_delta.md","07_deployment-and-operations/SEC-2_threat-model_and_data-flow.md") or (p.startswith('10_') and 'REG-POSTURE' not in p and not p.endswith('INDEX.md')) or (p.startswith('11_prompts/') and 'PROMPT-HARDEN' not in p) or p.startswith('.github/') or p in ('.gitignore','README.md','00_inventory.txt'))]
for p in w8ext: T(f'T-{n}','W8',p,'W8 ext — ' + ('skeleton (A-001 glob)' if 'repo-skeletons' in p else ('10_ (BSQ-0704; EX-5)' if p.startswith('10_') else ('11_ prompt' if p.startswith('11_') else ('07_ sprint-1 delta' if p.startswith('07_') else 'repository file'))))); n+=1
T('T-110','W9','(corpus) corpus-side artifacts — in-account only; no path in tree','ESCALATED placeholder until DEC-12 + credentials'); T('T-111','W9','(external) HeyDoc instruction-bearing files — Arepo-Medtech/Makoha below-README [NEEDS SOURCE]','W9 ext — row 73 (DEC-12 / G-08)')
T('T-120','W10','04_hardening/MAJOR_TASK_2_anti-laziness-hardening-directive.md','directive (retained verbatim; companion set + retention proof)'); T('T-121','W10','04_hardening/HARDEN-1_coverage_ledger_seed.md','HARDEN-1 (v1.0 T-121 collapsed HARDEN-1/2/3; expanded below)'); T('T-122','W10','01_north-star-and-transformation/MET-1_metamorphosis_plan_v1.0.md','MET set (v1.0 T-122 collapsed; expanded below)')
n=700
for p,nt in [("04_hardening/HARDEN-2_hardening_spec.md","W10 ext — from T-121"),("04_hardening/HARDEN-3_hardening_plan_worklist.md","W10 ext — from T-121"),("04_hardening/HARDEN-1.1_coverage_ledger_seed_delta.md","W10 ext — sprint-1"),("04_hardening/HARDEN-2.1_spec_census_and_self-audit_delta.md","W10 ext — sprint-1"),("04_hardening/HARDEN-3.1_task_register_delta.md","W10 ext — sprint-1 (this file)"),("01_north-star-and-transformation/MET-1.1_metamorphosis_plan_delta.md","W10 ext — from T-122"),("01_north-star-and-transformation/MET-2_conflict_and_decision_register.md","W10 ext — from T-122"),("01_north-star-and-transformation/MET-2.1_decision_register_delta.md","W10 ext — no v1.0 task"),("01_north-star-and-transformation/MET-3_traceability_map.md","W10 ext — from T-122"),("01_north-star-and-transformation/MET-4_gap_analysis_and_roadmap.md","W10 ext — from T-122"),("00_MANIFEST.md","W10 ext — manifest (CC-8)"),("04_hardening/INDEX.md","W10 ext — INDEX-04"),("05_registers-and-contracts/INDEX.md","W10 ext — INDEX-05"),("06_repositories/INDEX.md","W10 ext — INDEX-06"),("07_deployment-and-operations/INDEX.md","W10 ext — INDEX-07"),("08_research/INDEX.md","W10 ext — INDEX-08"),("09_diagrams/INDEX.md","W10 ext — INDEX-09"),("10_regulatory-execution/INDEX.md","W10 ext — INDEX-10"),("11_prompts/PROMPT-HARDEN_mt2_pass_launch.md","W10 ext — the pass's own launch prompt")]:
    T(f'T-{n}','W10',p,nt); n+=1
for tid,nt in [('T-130','cross-portfolio integrity sweep AFTER last edit — all refs, shared IDs, partitions; scope includes 10_ (EX-5)'),('T-131','/ship gate (shipping-and-launch) on the final portfolio state'),('T-132','wire checks into CI (ratchet; MT2 §7(4))')]:
    tasks.append(dict(tid=tid,wave='W11',path='— (process task over the whole tree; no single artifact)',rows='all',cls='—',skills='shipping-and-launch; ci-cd-and-automation; security-and-hardening; code-review-and-quality; doubt-driven-development',exit='sweep output recorded; /ship output; CI configuration diff',owner='MT2 operator (DEC-10) [NEEDS DEFINITION]',note=nt))
# checks
orig=set(['T-000']+[f'T-{i:03d}' for i in list(range(1,6))+[10,11,20,21]+list(range(30,46))+list(range(50,63))+list(range(70,73))+list(range(80,96))+list(range(100,108))+[110]+list(range(120,123))+list(range(130,133))])
ids=[t['tid'] for t in tasks]; dup=[i for i,c in collections.Counter(ids).items() if c>1]
present=orig&set(ids); missing_orig=sorted(orig-set(ids))
artifact_tasks=[t for t in tasks if not t['path'].startswith(('(','—'))]
paths_tasked=set(t['path'] for t in artifact_tasks); allfiles=set(D['allfiles']); untasked=sorted(allfiles-paths_tasked); dupe_paths=[p for p,c in collections.Counter(t['path'] for t in artifact_tasks).items() if c>1]
exists=sum(1 for t in artifact_tasks if os.path.isfile(t['path']))
wavecount=collections.Counter(t['wave'] for t in tasks)
def ttbl(ts):
    out=["| task | wave | artifact_path | HARDEN-1/1.1 row | class | mapped skills (MT2 §2.2 / HARDEN-2) | exit evidence | owner (role) | state | note |","|---|---|---|---|---|---|---|---|---|---|"]
    for t in ts: out.append(f"| `{t['tid']}` | {t['wave']} | {'`'+t['path']+'`' if not t['path'].startswith(('(','—')) else esc(t['path'])} | {t['rows']} | {t['cls']} | {esc(t['skills'])} | {esc(t['exit'])} | {esc(t['owner'])} | PENDING | {esc(t['note'])} |")
    return "\n".join(out)
h31=f"""---
doc_id: HARDEN-3.1
title: "HARDEN-3.1 — task register delta: one task per artifact, wave-assigned, with row, class, skills, exit evidence and owner"
version: "1.1-delta"
date: "2026-09-05"
status: "Plan delta; no task started; every task PENDING (pre-pass placeholder). HARDEN-3 v1.0 is preserved verbatim beside this file; read HARDEN-3 through this file. Every T-nnn HARDEN-3 v1.0 mints appears here exactly once; extension ids (T-140+ W1, 150+ W3, 160+ W5, 180+ W6, 400+ W8, 700+ W10) are Proposed and marked. This is a plan delta, not an R29 write (law 6). The pass runs from this register via PROMPT-HARDEN (draft) only after DEC-10/DEC-11 and row zero."
supersedes: "nothing — read HARDEN-3 through this file"
applies_to: "04_hardening/HARDEN-3_hardening_plan_worklist.md"
change_policy: "Additive delta per the MET-1.1 pattern; v1.0 T ids retained; wave order W0–W11 unchanged; W1/W3/W4/W5/W6/W8/W9/W10 gain extension tasks (marked 'ext')"
req_prefix: T
req_count: {len(tasks)}
---

# HARDEN-3.1 — task register delta

## D-1 — statement

HARDEN-3 v1.0 minted T-000..T-132 as ranges inside wave cells ("T-100..107: 05_/06_/07_/08_
documents"); no per-task row named an artifact path, class, skills, exit evidence or owner
(survey-2 BSQ-0006), and no task covered 10_ (12 files), 11_ ({sum(1 for t in tasks if t['path'].startswith('11_'))} prompts), R30.1/R30.2, MET-2.1,
the 03_ additions or the 02_ briefing (BSQ-0106/0204/0704). This delta expands every wave
range into one row per artifact (MT2 §3 — no batching) against the rows of HARDEN-1 +
HARDEN-1.1, and adds Proposed extension tasks for every artifact that had none. Wave order
and the reasons in HARDEN-3 v1.0 stand; EX-5's W11 scope (10_ included) is honoured by
placing every 10_ file in W3 (posture) or W8 (extension) **before** W11.

Reconciliations recorded (not silent): (a) W1 and W8 both named 05_ in v1.0 — 05_ originals
stay in W1, 05_ regulatory seed deltas move to W3 with T-021; (b) v1.0 W4 says "sixteen
tasks" for 19 named artifacts — T-030..045 are the sixteen HARDEN-1 rows 11–26 name (A–L,
variant 1b, variant 2, harness, grounding annex); Arch, Primer 0 and the integration report
take T-046..048 (proposed DEF row in 00_MANIFEST A-004); (c) T-121 and T-122 each collapsed
several artifacts — expanded into W10 extension tasks; (d) T-072 "html + mermaid sources"
expanded into T-072..T-076 (+ sprint-1 successors T-180..T-183).

Rule per task (HARDEN-3 v1.0 l.26, unchanged): load mapped skills per HARDEN-2 class bar;
doubt-driven-development ALWAYS ON; ledger row closed HARDENED-with-evidence or
ESCALATED-with-blocker before the next task starts.

## D-2 — task register ({len(tasks)} tasks)

{ttbl(tasks)}

## Wave census

| Wave | Tasks | v1.0 ids present | Extension ids |
|---|---|---|---|
""" + "\n".join(f"| {w} | {wavecount[w]} | {sum(1 for t in tasks if t['wave']==w and t['tid'] in orig)} | {sum(1 for t in tasks if t['wave']==w and t['tid'] not in orig)} |" for w in ['W0','W1','W2','W3','W4','W5','W6','W7','W8','W9','W10','W11']) + f"""
| **Total** | **{len(tasks)}** | **{len(present)}** | **{len(tasks)-len(present)}** |

## ID census and self-audit (script output, `{RUN}/tools/render_harden.py`, 2026-09-05)

```
T ids: {len(ids)} rows, {len(set(ids))} unique, duplicates: {dup}
HARDEN-3 v1.0 ids expected (000; 001–005; 010–011; 020–021; 030–045; 050–062; 070–072; 080–095; 100–107; 110; 120–122; 130–132): {len(orig)}
  present exactly once: {len(present)}/{len(orig)}   missing: {missing_orig}
artifact tasks: {len(artifact_tasks)} | distinct artifact paths: {len(paths_tasked)} | duplicate paths: {dupe_paths}
files in tree (HARDEN-1.1 scope rule) without a task: {len(untasked)} {untasked[:5]}
artifact paths existing on disk at generation: {exists}/{len(artifact_tasks)} (the remainder are sprint-1 INDEX/HARDEN files written after this register; verified at seal — RUN-REPORT)
process tasks without a single artifact (W0 engine, W9 corpus/external, W11 sweep/ship/CI): {sum(1 for t in tasks if t['path'].startswith(('(','—')))}
```

Acceptance (BSQ-0006/0106/0704): every file under 00_–11_ (scope rule) appears exactly once; every 10_ file has a task before W11 — PASS ({sum(1 for t in tasks if t['path'].startswith('10_'))} tasks in W3/W8). HARDEN-3 v1.0 byte-identical (CHECKSUMS_BEFORE/AFTER).
"""
open("04_hardening/HARDEN-3.1_task_register_delta.md","w",encoding="utf-8").write(h31)
json.dump(tasks,open(f"{RUN}/tasks.json","w"),indent=1)
print(f"HARDEN-1.1: {len(rows)} rows, {len(h11.encode())} B | HARDEN-3.1: {len(tasks)} tasks, {len(h31.encode())} B | orig present {len(present)}/{len(orig)} missing {missing_orig} dup {dup} untasked {len(untasked)} dupe_paths {dupe_paths}")
